### ISSUE TITLE
Premium cluster

### ISSUE THREAD

**Issue by jakubigla** [afuyo/hdinsigt-install-apache-atlas#1]
Hi, Have you got that working with domain joined permium cluster? 
Can't query solr API due to 401 error...

**Comment by afuyo** [comment]
Hej Jakub,
no I have not yet tried that. It is although in the pipeline. I'd be
grateful if you share you experience around that. Apparently Microsoft
discourages to install anything on premium cluster. Do you try to run Atlas
or just Solr?

Best Regards
Artur

**Comment by jakubigla** [comment]
I need to install Apache Atlas so the government organisation I'm contracting for can do data governance, thus it's a must for us. Because the cluster is kerberized I guess I need to use this: https://lucene.apache.org/solr/guide/6_6/kerberos-authentication-plugin.html

**Comment by afuyo** [comment]
One thing worth mentioning is that if you want to configure Atlas for hive hooks then you either do it manually through Ambari or add this in your arm templates: 
"hive-site": {
      "hive.exec.post.hooks": "org.apache.atlas.hive.hook.HiveHook",
		  },
		"hive-env":{ 
      
                                  "content" : "\n export HIVE_AUX_JARS_PATH=/usr/hdp/current/atlas-client/hook/hive \n"
                    }
